[package]
name = "reset_passwd_async"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
futures = "0.3.31"
rand = "0.8"
tokio = { version = "1.49.0", features = ["full"] }
chrono = "0.4"
umya-spreadsheet = "2.3.3"
